# Generated by Django 2.2.1 on 2019-11-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='기업 이름')),
                ('url', models.URLField(verbose_name='홈페이지 주소')),
                ('photo', models.ImageField(upload_to='staff/advertising')),
            ],
            options={
                'verbose_name': '광고',
                'verbose_name_plural': '광고',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('hits', models.IntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '관리자 게시판',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='분류')),
            ],
            options={
                'verbose_name': '분류',
                'verbose_name_plural': '게시판 분류',
            },
        ),
        migrations.CreateModel(
            name='DonationOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='기부단체명')),
                ('desc', models.TextField(verbose_name='단체설명')),
                ('photo', models.ImageField(upload_to='staff/donation/', verbose_name='사진')),
                ('url', models.URLField(max_length=250, verbose_name='홈페이지 주소')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('is_donate', models.BooleanField(default=False, verbose_name='이달 기부단체')),
            ],
            options={
                'verbose_name': '기부단체',
                'verbose_name_plural': '기부단체',
            },
        ),
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default=None, max_length=15, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('question', models.TextField(verbose_name='질문')),
                ('lock', models.BooleanField(default=False, verbose_name='비공개')),
                ('answer', models.TextField(null=True, verbose_name='답변')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문 게시판',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='경품이름')),
                ('photo', models.ImageField(null=True, upload_to='staff/ticket')),
            ],
            options={
                'verbose_name': '응모권',
                'verbose_name_plural': '응모권',
            },
        ),
    ]
