# Generated by Django 2.2.1 on 2019-11-02 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='질문자'),
        ),
        migrations.AddField(
            model_name='hitcount',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Board'),
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Category', verbose_name='분류'),
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='게시자'),
        ),
        migrations.CreateModel(
            name='DonationOrgSelect',
            fields=[
            ],
            options={
                'verbose_name': '기부단체 선택률',
                'verbose_name_plural': '기부단체 선택률',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('staff.donationorg',),
        ),
    ]
