# Generated by Django 2.2.1 on 2019-11-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='퀴즈 푼 날짜')),
                ('myAnswer', models.CharField(max_length=1, verbose_name='회원 답')),
            ],
            options={
                'verbose_name': '회원퀴즈',
                'verbose_name_plural': '회원퀴즈',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='퀴즈내용')),
                ('answer', models.CharField(choices=[('O', 'O'), ('X', 'X'), ('N', 'N')], max_length=1, null=True, verbose_name='답')),
                ('difficulty', models.CharField(max_length=5, verbose_name='난이도')),
            ],
            options={
                'verbose_name': '퀴즈',
                'verbose_name_plural': '퀴즈',
            },
        ),
        migrations.CreateModel(
            name='QuizSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='퀴즈주제')),
                ('photo', models.ImageField(null=True, upload_to='quiz/quizSub_img/', verbose_name='사진')),
            ],
            options={
                'verbose_name': '퀴즈주제',
                'verbose_name_plural': '퀴즈주제',
            },
        ),
    ]
