# Generated by Django 2.2.1 on 2019-11-02 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0001_initial'),
        ('user', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweeds',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원이름'),
        ),
        migrations.AddField(
            model_name='userweeds',
            name='weeds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Weeds', verbose_name='잡초'),
        ),
        migrations.AddField(
            model_name='seedstate',
            name='growth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Growth', verbose_name='상태명'),
        ),
        migrations.AddField(
            model_name='seedstate',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Seed', verbose_name='씨앗명'),
        ),
        migrations.AddField(
            model_name='plantstate',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Item', verbose_name='도구'),
        ),
        migrations.AddField(
            model_name='diary',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='staff.DonationOrg', verbose_name='기부단체'),
        ),
        migrations.AddField(
            model_name='diary',
            name='plantState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.PlantState', verbose_name='작물상태'),
        ),
        migrations.AddField(
            model_name='diary',
            name='seedState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.SeedState', verbose_name='씨앗상태'),
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='회원이름'),
        ),
    ]
