# Generated by Django 2.2.1 on 2019-11-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20191102_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='count',
            field=models.IntegerField(default=50, verbose_name='씨앗재고'),
            preserve_default=False,
        ),
    ]
